// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNnMQZSIyV8M0VymsIQIdjhuJSLPM-F4',
    appId: '1:288488564202:web:54dcf34bb075267270fe93',
    messagingSenderId: '288488564202',
    projectId: 'smart-samai',
    authDomain: 'smart-samai.firebaseapp.com',
    storageBucket: 'smart-samai.firebasestorage.app',
    measurementId: 'G-M7PD9V0G5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzZWqT5iYOI8MzvkWJMN62LQNBH9UQj8',
    appId: '1:288488564202:android:09671d93146650f570fe93',
    messagingSenderId: '288488564202',
    projectId: 'smart-samai',
    storageBucket: 'smart-samai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-8WoTLp9TNB74z8uE7tw7ZyHYA2Kbvfk',
    appId: '1:288488564202:ios:6b67bc26895b624270fe93',
    messagingSenderId: '288488564202',
    projectId: 'smart-samai',
    storageBucket: 'smart-samai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-8WoTLp9TNB74z8uE7tw7ZyHYA2Kbvfk',
    appId: '1:288488564202:ios:6b67bc26895b624270fe93',
    messagingSenderId: '288488564202',
    projectId: 'smart-samai',
    storageBucket: 'smart-samai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCNnMQZSIyV8M0VymsIQIdjhuJSLPM-F4',
    appId: '1:288488564202:web:d94fc112232af5a270fe93',
    messagingSenderId: '288488564202',
    projectId: 'smart-samai',
    authDomain: 'smart-samai.firebaseapp.com',
    storageBucket: 'smart-samai.firebasestorage.app',
    measurementId: 'G-TTDZ4G7EFC',
  );

}